version: '3.3'

services:
  jenkins:
    image: jinternals/jenkins:1.0-SNAPSHOT
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./data/jenkins_home/:/var/jenkins_home
      - ./data/tools/:/var/tools
#    secrets:
#      - artifactoryPassword
    networks:
      jenkins-network:
        ipv4_address: 10.8.0.2

#secrets:
#  artifactoryPassword:
#    file: ./config/jenkins/artifactoryPassword

networks:
  jenkins-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/16