apiVersion: v1
kind: Secret
metadata:
  name: jenkins-job-builder
  namespace: jenkins
type: Opaque
stringData:
  jenkins_jobs.ini: |-
    [jenkins]
    user=jenkins
    password=jenkins
    print_job_urls=true
    url=http://jenkins-ui.jenkins:8080
